/* generated by gtkcooker (http://www.nongnu.org/gtkcooker) */

#include <gtk/gtk.h>
#include "gui.h"



#include <string.h>
#include "err.h"

void go_gui(login_gui *l, const char *img, int len)
{
  gtk_init(0, 0);
  init_login_gui(l, img, len);
  gtk_widget_show_all(l->w);
  gtk_main();
}


static void _1(GtkEntry *_widget, login_gui *this)
{
  {
    this->in = strdup(gtk_entry_get_text(GTK_ENTRY(this->t)));
    if (!this->in) OOM();
    gtk_widget_destroy(this->w);
    gtk_main_quit();
  }
}

/* returns -1 on error, 0 if everything is fine */
int init_login_gui(login_gui *this, const char *img, int l)
{
  GtkWidget *_0;
  GtkWidget *img_box;
  GtkWidget *_2;
  GtkWidget *_3;

  this->w = gtk_window_new(GTK_WINDOW_TOPLEVEL);
  {
    GdkGeometry _geo; _geo.min_width = _geo.min_height = 1;
    gtk_window_set_geometry_hints(GTK_WINDOW(this->w),
        (GtkWidget *)this->w, &_geo, GDK_HINT_MIN_SIZE);
  }
  _0 = gtk_vbox_new(FALSE, 0);
  this->t = gtk_entry_new();
  img_box = gtk_vbox_new(FALSE, 0);
  _2 = gtk_hbox_new(FALSE, 0);
  _3 = gtk_hbox_new(FALSE, 0);

  gtk_container_add(GTK_CONTAINER(this->w), (GtkWidget *)_0);
  gtk_box_pack_start(GTK_BOX(_0), (GtkWidget *)_2, FALSE, FALSE, 0);
  gtk_box_pack_start(GTK_BOX(_0), (GtkWidget *)_3, TRUE, TRUE, 0);
  gtk_box_pack_start(GTK_BOX(_2), (GtkWidget *)img_box, FALSE, FALSE, 0);
  gtk_box_pack_start(GTK_BOX(_3), (GtkWidget *)this->t, TRUE, TRUE, 0);


  this->t_activate = g_signal_connect(this->t, "activate", G_CALLBACK(_1), this);

  {
    GtkWidget *im;
    GInputStream *in = g_memory_input_stream_new_from_data(img, l, NULL);
    GdkPixbuf *b = gdk_pixbuf_new_from_stream(in, NULL, NULL);
    if (!b) { printf("bad image\n"); exit(1); }
    g_input_stream_close(in, NULL, NULL);
    im = gtk_image_new_from_pixbuf(b);
    g_object_unref(b);
    gtk_container_add(GTK_CONTAINER(img_box), im);
  }

  return 0;
}

